name: Deploy Hugo

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest

      - name: Build 
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          #personal_token: ${{ secrets.personal_token }}
          PUBLISH_BRANCH: gh_pages
          PUBLISH_DIR: ./public
          commit_message: "commit_message"
